model_name: VBD

# Data Config
train_data_path: /root/single_agent_subset/training/processed
val_data_path: /root/single_agent_subset/validation/processed
anchor_path: /robin-west/VBD/vbd/data/cluster_64_center_dict.pkl
log_dir: /robin-west/VBD/train_log_0221


# Wandb Config
use_wandb: True
username: luw015
project: vbd_0221

# Checkpoint Config
init_from: /robin-west/VBD/train_log_0221/VBD_20250222041653/epoch=35.ckpt

# Model Config
agents_len: 32
future_len: 80
action_len: 2
encoder_layers: 6
prediction_type: sample
encoder_version: v2 # v1: GRU, v2: MLP

# Diffusion Params
diffusion_steps: 50
schedule_type: cosine
schedule_s: 0
schedule_e: 1
schedule_tau: 1

action_mean: [0.0, 0.0]
action_std: [1.0, 0.15]
clamp_value: 5.0

# Training Params
seed: 42
batch_size: 16
num_workers: 16
lr: 0.0002
weight_decay: 0.01
epochs: 64
lr_warmup_step: 1000
lr_step_freq: 1000
lr_step_gamma: 0.98

train_encoder: True
train_denoiser: True
train_predictor: False
with_predictor: False

predict_ego_only: True
validate_full_sample: True
validate_num_samples: 6
input_type: trajectory

enable_prior_means: False
training_action_labels_path: /root/single_agent_subset/training/action_labels.pkl
validation_action_labels_path: /root/single_agent_subset/validation/action_labels.pkl